### ISSUE TITLE
Deal with dependency hell

### ISSUE THREAD

**Issue by michel2323** [exanauts/ProxAL.jl#11]
We need to find a mechanism to reduce dependencies and not me dependent on MadNLP, ExaPF, Ipopt, and Hiop, at the same time.

**Comment by frapac** [comment]
I would suggest the following: 
- in `test/`, we test both `ExaBlockModel` and `JuMPBlockModel` using Ipopt as optimization solver. The reason is that once the model specified, the results should be the same no matter the optimization packages we are using in the backend. If that's not the case, then this is a bug related to ExaPF or JuMP, and should be catched inside the CI of these packages.
- we could create a new directory  `benchmarks/` where we could test all the solvers we want and compare their relative performances together. 

As `benchmarks/` would have its own `Project.toml`, that would allow to get rid of the dependencies wrt `MadNLP` and `Hiop`

**Comment by michel2323** [comment]
Removed most dependencies and added `deps/deps.jl` script to full ExaTron and ExaPF.
